# .swiftlint.yml for HealthAI 2030 UI
# Enforces code style and best practices for Swift codebase

opt_in_rules:
  - accessibility_label_for_image
  - accessibility_trait_for_button
  - dynamic_type_usage
  - empty_count
  - explicit_init
  - file_length
  - force_cast
  - force_try
  - function_body_length
  - identifier_name
  - line_length
  - mark
  - missing_docs
  - nesting
  - private_outlet
  - redundant_optional_initialization
  - return_arrow_whitespace
  - sorted_imports
  - switch_case_on_newline
  - trailing_whitespace
  - type_body_length
  - vertical_parameter_alignment
  - vertical_whitespace

excluded:
  - Carthage
  - Pods
  - build
  - Coverage
  - fastlane
  - Scripts

line_length:
  warning: 120
  error: 200

missing_docs:
  warning: true
  error: false

# Add more rules as needed for project standards
