# SwiftLint Configuration for HealthAI 2030

# Included and Excluded directories
included:
  - HealthAI\ 2030
  - Tests

excluded:
  - HealthAI\ 2030.xcodeproj
  - HealthAI\ 2030/Assets.xcassets
  - HealthAI\ 2030/Documentation
  - .build
  - Carthage
  - Pods

# Analyzer Rules (require compilation)
analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import

# Disabled Rules
disabled_rules:
  - line_length # Handled by opt_in_rules with custom length
  - trailing_whitespace # Auto-fixed by Xcode
  - todo # Allow TODO comments during development
  - force_cast # Sometimes necessary for Core Data
  - type_name # Allow single character type names for generics

# Opt-in Rules (not enabled by default)
opt_in_rules:
  - accessibility_label_for_image
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - missing_docs
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - no_space_in_method_call
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

# Custom Rule Configuration
line_length:
  warning: 120
  error: 140
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 400
  error: 500

function_body_length:
  warning: 40
  error: 60

function_parameter_count:
  warning: 5
  error: 8

type_body_length:
  warning: 250
  error: 350

cyclomatic_complexity:
  warning: 10
  error: 15

nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 3
    error: 4

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - x
    - y
    - z
    - i
    - j
    - k

# Custom Rules
custom_rules:
  # Enforce proper spacing around operators
  operator_spacing:
    name: "Operator Spacing"
    regex: '([^!<>=\s])([<>=]+)([^<>=\s])'
    message: "Operators should be surrounded by spaces"
    severity: warning
    
  # Discourage force try
  force_try:
    name: "Force Try"
    regex: 'try!'
    message: "Avoid using force try. Use proper error handling instead."
    severity: warning
    
  # Require documentation for public APIs
  public_documentation:
    name: "Public Documentation"
    regex: '^[ \t]*public[ \t]+(?:class|struct|enum|protocol|func|var|let)(?![^{]*\/\/\/)'
    message: "Public declarations should be documented"
    severity: warning

# File Header Template
file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*\.swift
                    \/\/  HealthAI 2030
                    \/\/
                    \/\/  Created by .* on \d{1,2}\/\d{1,2}\/\d{2,4}\.
                    \/\/

# Reporter Configuration
reporter: "xcode"

# Build Time Analyzer
compilation_mode: wholemodule