# SwiftLint Configuration for HealthAI 2030

# Included and Excluded directories
included:
  - HealthAI\ 2030
  - Tests

excluded:
  - HealthAI\ 2030.xcodeproj
  - HealthAI\ 2030/Assets.xcassets
  - HealthAI\ 2030/Documentation
  - .build
  - Carthage
  - Pods
  - Packages

# Analyzer Rules (require compilation)
analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import

# Disabled Rules
disabled_rules:
  - line_length # Handled by opt_in_rules with custom length
  - trailing_whitespace # Auto-fixed by Xcode
  - todo # Allow TODO comments during development
  - force_cast # Sometimes necessary for Core Data
  - type_name # Allow single character type names for generics

# Opt-in Rules (not enabled by default)
opt_in_rules:
  - accessibility_label_for_image
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - empty_count
  - explicit_init
  - fatal_error_message
  - first_where
  - force_try
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - nimble_operator
  - operator_usage_whitespace
  - overridden_super_call
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - redundant_optional_initialization
  - redundant_set_access_control
  - sorted_first_last
  - switch_case_on_newline
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Custom Rule Configuration
line_length:
  warning: 120
  error: 140
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 400
  error: 500

function_body_length:
  warning: 40
  error: 60

function_parameter_count:
  warning: 5
  error: 8

type_body_length:
  warning: 250
  error: 350

cyclomatic_complexity:
  warning: 10
  error: 15

nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 3
    error: 4

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - x
    - y
    - z
    - i
    - j
    - k

# Custom Rules
custom_rules:
  # Enforce proper spacing around operators
  operator_spacing:
    name: "Operator Spacing"
    regex: '([^!<>=\s])([<>=]+)([^<>=\s])'
    message: "Operators should be surrounded by spaces"
    severity: warning
    
  # Discourage force try
  force_try:
    name: "Force Try"
    regex: 'try!'
    message: "Avoid using force try. Use proper error handling instead."
    severity: warning
    
  # Require documentation for public APIs
  public_documentation:
    name: "Public Documentation"
    regex: '^[ \t]*public[ \t]+(?:class|struct|enum|protocol|func|var|let)(?![^{]*\/\/\/)'
    message: "Public declarations should be documented"
    severity: warning

# File Header Template
file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*\.swift
                    \/\/  HealthAI 2030
                    \/\/
                    \/\/  Created by .* on \d{1,2}\/\d{1,2}\/\d{2,4}\.
                    \/\/

# Reporter Configuration
reporter: "xcode"

# Build Time Analyzer
compilation_mode: wholemodule