# HealthAI 2030 SwiftLint Configuration
# Aligned with Apple HIG and modern iOS development practices

disabled_rules:
  - trailing_whitespace # Handled by editor
  - todo # Allow TODO comments during development

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - unused_private_declaration
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

included:
  - Source
  - Tests

excluded:
  - Archive
  - Scripts
  - Documentation
  - .build
  - Carthage
  - Pods
  - vendor

# Rule configurations
line_length:
  warning: 120
  error: 150

file_length:
  warning: 500
  error: 800

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 10
  error: 20

large_tuple:
  warning: 3
  error: 4

# Custom rules for HealthAI 2030
custom_rules:
  no_print:
    name: "No Print Statements"
    regex: 'print\('
    message: "Use Logger instead of print statements"
    severity: warning
  
  no_force_cast:
    name: "No Force Casting"
    regex: ' as! '
    message: "Use safe casting with 'as?' instead of 'as!'"
    severity: error
