apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthai2030
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthai2030
  template:
    metadata:
      labels:
        app: healthai2030
    spec:
      containers:
      - name: healthai2030
        image: healthai2030:latest
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: healthai2030-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: healthai2030-service
spec:
  type: ClusterIP
  selector:
    app: healthai2030
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
