apiVersion: v1
kind: Secret
metadata:
  name: healthai2030-secrets
  namespace: healthai2030
  annotations:
    description: "HealthAI 2030 application secrets - Loaded from secure vault"
    security.healthai.com/rotation-policy: "30d"
    security.healthai.com/encryption: "AES-256-GCM"
    security.healthai.com/source: "aws-secrets-manager"
stringData:
  # Secrets loaded from AWS Secrets Manager
  # No hardcoded values - all secrets are externalized
  DATABASE_URL: "${DATABASE_URL}"
  API_KEY: "${API_KEY}"
  SECRET_KEY: "${SECRET_KEY}"
  SENTRY_DSN: "${SENTRY_DSN}"
  AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
  AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
  JWT_SECRET: "${JWT_SECRET}"
  ENCRYPTION_KEY: "${ENCRYPTION_KEY}"
  OAUTH_CLIENT_SECRET: "${OAUTH_CLIENT_SECRET}"
  CERTIFICATE_PINNING_KEY: "${CERTIFICATE_PINNING_KEY}"
  RATE_LIMITING_SECRET: "${RATE_LIMITING_SECRET}"
  SECURITY_MONITORING_KEY: "${SECURITY_MONITORING_KEY}"
