import Foundation

/// Represents the Digital Twin, a dynamic, predictive model of a user's health.
/// This structure will be the central repository for all data related to the twin.
public struct DigitalTwin: Codable, Identifiable {
    public let id: UUID
    
    /// The date this version of the twin was created or last updated.
    var lastUpdated: Date
    
    // MARK: - Core Data Components
    
    /// High-resolution biometric data.
    var biometricData: BiometricProfile
    
    /// Genomic data profile (optional and user-provided).
    var genomicData: GenomicProfile?
    
    /// Clinical data from EHRs and lab results.
    var clinicalData: ClinicalProfile?
    
    /// Lifestyle data including nutrition, exercise, and sleep.
    var lifestyleData: LifestyleProfile
    
    /// Environmental data context.
    var environmentalContext: EnvironmentalProfile
    
    /// Health predictions generated by the Pre-Symptomatic Analytics Core.
    var healthPredictions: [HealthPrediction]
    
    // MARK: - Initializer
    
    public init(id: UUID = UUID(),
                lastUpdated: Date = Date(),
                biometricData: BiometricProfile,
                genomicData: GenomicProfile? = nil,
                clinicalData: ClinicalProfile? = nil,
                lifestyleData: LifestyleProfile,
                environmentalContext: EnvironmentalProfile,
                healthPredictions: [HealthPrediction] = []) {
        self.id = id
        self.lastUpdated = lastUpdated
        self.biometricData = biometricData
        self.genomicData = genomicData
        self.clinicalData = clinicalData
        self.lifestyleData = lifestyleData
        self.environmentalContext = environmentalContext
        self.healthPredictions = healthPredictions
    }
}

// MARK: - Sub-structures for Data Organization

/// A profile of the user's biometric data.
public struct BiometricProfile: Codable {
    // Placeholder for detailed biometric properties
    var heartRateVariability: [Double]
    var restingHeartRate: [Double]
    var bloodOxygenSaturation: [Double]
    // ... other biometric data points
}

/// A profile of the user's genomic data.
public struct GenomicProfile: Codable {
    // Placeholder for genomic markers
    var geneticMarkers: [String: String] // e.g., ["rs12345": "A/G"]
}

/// A profile of the user's clinical data.
public struct ClinicalProfile: Codable {
    // Placeholder for clinical records
    var labResults: [String: String] // e.g., ["Cholesterol": "200 mg/dL"]
}

/// A profile of the user's lifestyle data.
public struct LifestyleProfile: Codable {
    // Placeholder for lifestyle information
    var averageSleepDuration: TimeInterval
    var weeklyExerciseMinutes: Int
}

/// A profile of the user's environmental context.
public struct EnvironmentalProfile: Codable {
    // Placeholder for environmental data
    var airQualityIndex: Int
    var pollenCount: Int
}