import Foundation
import SwiftData

/// Represents a type of health data (e.g., sleep, steps, heart rate).
public enum HealthDataType: String, Codable, CaseIterable, Identifiable {
    public var id: String { self.rawValue }
    case sleepHours = "Sleep Hours"
    case steps = "Steps"
    case heartRate = "Heart Rate"
    case bloodPressure = "Blood Pressure"
    case spo2 = "SpO2"
    case ecg = "ECG"
    case temperature = "Temperature"
    case genomicData = "Genomic Data"
    case clinicalRecord = "Clinical Record"
    case nutrition = "Nutrition"
    case exercise = "Exercise"
    case medicationAdherence = "Medication Adherence"
    case environmentalAirQuality = "Environmental Air Quality"
    case environmentalPollen = "Environmental Pollen"
    case environmentalUVIndex = "Environmental UV Index"
    case custom = "Custom Data" // For user-defined or future data types
    case heartRateVariability = "Heart Rate Variability"
    case bloodGlucose = "Blood Glucose"
    case weight = "Weight"
    case bodyFatPercentage = "Body Fat Percentage"
    case leanBodyMass = "Lean Body Mass"
    case height = "Height"
    case bodyMassIndex = "Body Mass Index"
    case waistCircumference = "Waist Circumference"
    case sleepDuration = "Sleep Duration"
    case deepSleepDuration = "Deep Sleep Duration"
    case remSleepDuration = "REM Sleep Duration"
    case awakeDuration = "Awake Duration"
    case sleepEfficiency = "Sleep Efficiency"
    case sleepLatency = "Sleep Latency"
    case sleepInterruptions = "Sleep Interruptions"
    case sleepConsistency = "Sleep Consistency"
    case workoutDuration = "Workout Duration"
    case caloriesBurned = "Calories Burned"
    case distance = "Distance"
    case elevationGained = "Elevation Gained"
    case activeCalories = "Active Calories"
    case restingCalories = "Resting Calories"
    case proteinIntake = "Protein Intake"
    case carbIntake = "Carbohydrate Intake"
    case fatIntake = "Fat Intake"
    case waterIntake = "Water Intake"
    case caffeineIntake = "Caffeine Intake"
    case alcoholIntake = "Alcohol Intake"
    case stressScore = "Stress Score"
    case mindfulnessMinutes = "Mindfulness Minutes"
    case mood = "Mood"
    case cognitivePerformance = "Cognitive Performance"
    case socialInteraction = "Social Interaction"
    case screenTime = "Screen Time"
    case medicationDosage = "Medication Dosage"
    case painLevel = "Pain Level"
    case symptomSeverity = "Symptom Severity"
    case environmentalHumidity = "Environmental Humidity"
    case environmentalPressure = "Environmental Pressure"
    case environmentalNoise = "Environmental Noise"
    case environmentalLight = "Environmental Light"
    case uvExposure = "UV Exposure"
    case airPollution = "Air Pollution"
    case pollenCount = "Pollen Count"
    case bloodOxygenSaturation = "Blood Oxygen Saturation"
    case bloodPressureSystolic = "Blood Pressure Systolic"
    case bloodPressureDiastolic = "Blood Pressure Diastolic"
    case bodyFatMass = "Body Fat Mass"
    case leanMass = "Lean Mass"
    case boneMass = "Bone Mass"
    case muscleMass = "Muscle Mass"
    case bodyWaterContent = "Body Water Content"
    case basalMetabolicRate = "Basal Metabolic Rate"
    case activeMetabolicRate = "Active Metabolic Rate"
    case heartRateRecovery = "Heart Rate Recovery"
    case vo2Max = "VO2 Max"
    case walkingAsymmetry = "Walking Asymmetry"
    case walkingDoubleSupport = "Walking Double Support"
    case walkingSpeed = "Walking Speed"
    case walkingStepLength = "Walking Step Length"
    case sixMinuteWalkDistance = "Six Minute Walk Distance"
    case appleWalkingSteadiness = "Apple Walking Steadiness"
    case environmentalAudioExposure = "Environmental Audio Exposure"
    case headphoneAudioExposure = "Headphone Audio Exposure"
    case handwashingDuration = "Handwashing Duration"
    case handwashingFrequency = "Handwashing Frequency"
    case numberOfFalls = "Number of Falls"
    case pushCount = "Push Count"
    case swimmingStrokeCount = "Swimming Stroke Count"
    case waterTemperature = "Water Temperature"
    case underwaterDepth = "Underwater Depth"
    case diveDuration = "Dive Duration"
    case atrialFibrillationHistory = "Atrial Fibrillation History"
    case electrocardiogram = "Electrocardiogram"
    case insulinDelivery = "Insulin Delivery"
    case bloodAlcoholContent = "Blood Alcohol Content"
    case forcedVitalCapacity = "Forced Vital Capacity"
    case forcedExpiratoryVolume1 = "Forced Expiratory Volume 1"
    case peakExpiratoryFlowRate = "Peak Expiratory Flow Rate"
    case inhalerUsage = "Inhaler Usage"
    case menstrualFlow = "Menstrual Flow"
    case ovulationTestResult = "Ovulation Test Result"
    case cervicalMucusQuality = "Cervical Mucus Quality"
    case sexualActivity = "Sexual Activity"
    case intermenstrualBleeding = "Intermenstrual Bleeding"
    case toothbrushingEvent = "Toothbrushing Event"
    case toothbrushingDuration = "Toothbrushing Duration"
    case uvIndex = "UV Index"
    case sleepCarbonDioxide = "Sleep Carbon Dioxide"
    case sleepSnoring = "Sleep Snoring"
    case sleepApneaEvents = "Sleep Apnea Events"
    case sleepRespiratoryDisturbances = "Sleep Respiratory Disturbances"
    case sleepHeartRate = "Sleep Heart Rate"
    case sleepTemperature = "Sleep Temperature"
    case sleepOxygenSaturation = "Sleep Oxygen Saturation"
    case sleepAmbientNoise = "Sleep Ambient Noise"
    case sleepAmbientLight = "Sleep Ambient Light"
    case sleepMovement = "Sleep Movement"
    case sleepPosition = "Sleep Position"
    case sleepEnvironmentTemperature = "Sleep Environment Temperature"
    case sleepEnvironmentHumidity = "Sleep Environment Humidity"
    case sleepEnvironmentPressure = "Sleep Environment Pressure"
    case sleepEnvironmentCO2 = "Sleep Environment CO2"
    case sleepEnvironmentVOC = "Sleep Environment VOC"
    case sleepEnvironmentPM25 = "Sleep Environment PM25"
    case sleepEnvironmentPM10 = "Sleep Environment PM10"
    case sleepEnvironmentTVOC = "Sleep Environment TVOC"
    case sleepEnvironmentFormaldehyde = "Sleep Environment Formaldehyde"
    case sleepEnvironmentRadon = "Sleep Environment Radon"
    case sleepEnvironmentCarbonMonoxide = "Sleep Environment Carbon Monoxide"
    case sleepEnvironmentNitrogenDioxide = "Sleep Environment Nitrogen Dioxide"
    case sleepEnvironmentOzone = "Sleep Environment Ozone"
    case sleepEnvironmentSulfurDioxide = "Sleep Environment Sulfur Dioxide"
    case sleepEnvironmentLead = "Sleep Environment Lead"
    case sleepEnvironmentParticulateMatter = "Sleep Environment Particulate Matter"
    case sleepEnvironmentVolatileOrganicCompounds = "Sleep Environment Volatile Organic Compounds"
    case sleepEnvironmentNitrousOxide = "Sleep Environment Nitrous Oxide"
    case sleepEnvironmentMethane = "Sleep Environment Methane"
    case sleepEnvironmentAmmonia = "Sleep Environment Ammonia"
    case sleepEnvironmentHydrogenSulfide = "Sleep Environment Hydrogen Sulfide"
    case sleepEnvironmentChlorine = "Sleep Environment Chlorine"
    case sleepEnvironmentHydrogenCyanide = "Sleep Environment Hydrogen Cyanide"
    case sleepEnvironmentHydrogenChloride = "Sleep Environment Hydrogen Chloride"
    case sleepEnvironmentHydrogenFluoride = "Sleep Environment Hydrogen Fluoride"
    case sleepEnvironmentHydrogenBromide = "Sleep Environment Hydrogen Bromide"
    case sleepEnvironmentHydrogenIodide = "Sleep Environment Hydrogen Iodide"
    case sleepEnvironmentHydrogenPeroxide = "Sleep Environment Hydrogen Peroxide"
    case sleepEnvironmentHydrogenSulfate = "Sleep Environment Hydrogen Sulfate"
    case sleepEnvironmentNitricAcid = "Sleep Environment Nitric Acid"
    case sleepEnvironmentSulfuricAcid = "Sleep Environment Sulfuric Acid"
    case sleepEnvironmentHydrochloricAcid = "Sleep Environment Hydrochloric Acid"
    case sleepEnvironmentHydrofluoricAcid = "Sleep Environment Hydrofluoric Acid"
    case sleepEnvironmentHydrobromicAcid = "Sleep Environment Hydrobromic Acid"
    case sleepEnvironmentHydriodicAcid = "Sleep Environment Hydriodic Acid"
    case sleepEnvironmentPerchloricAcid = "Sleep Environment Perchloric Acid"
    case sleepEnvironmentPhosphoricAcid = "Sleep Environment Phosphoric Acid"
    case sleepEnvironmentCarbonicAcid = "Sleep Environment Carbonic Acid"
    case sleepEnvironmentBoricAcid = "Sleep Environment Boric Acid"
    case sleepEnvironmentCitricAcid = "Sleep Environment Citric Acid"
    case sleepEnvironmentLacticAcid = "Sleep Environment Lactic Acid"
    case sleepEnvironmentMalicAcid = "Sleep Environment Malic Acid"
    case sleepEnvironmentTartaricAcid = "Sleep Environment Tartaric Acid"
    case sleepEnvironmentOxalicAcid = "Sleep Environment Oxalic Acid"
    case sleepEnvironmentAceticAcid = "Sleep Environment Acetic Acid"
    case sleepEnvironmentFormicAcid = "Sleep Environment Formic Acid"
    case sleepEnvironmentButyricAcid = "Sleep Environment Butyric Acid"
    case sleepEnvironmentPropionicAcid = "Sleep Environment Propionic Acid"
    case sleepEnvironmentValericAcid = "Sleep Environment Valeric Acid"
    case sleepEnvironmentCaproicAcid = "Sleep Environment Caproic Acid"
    case sleepEnvironmentCaprylicAcid = "Sleep Environment Caprylic Acid"
    case sleepEnvironmentCapricAcid = "Sleep Environment Capric Acid"
    case sleepEnvironmentLauricAcid = "Sleep Environment Lauric Acid"
    case sleepEnvironmentMyristicAcid = "Sleep Environment Myristic Acid"
    case sleepEnvironmentPalmiticAcid = "Sleep Environment Palmitic Acid"
    case sleepEnvironmentStearicAcid = "Sleep Environment Stearic Acid"
    case sleepEnvironmentArachidicAcid = "Sleep Environment Arachidic Acid"
    case sleepEnvironmentBehenicAcid = "Sleep Environment Behenic Acid"
    case sleepEnvironmentLignocericAcid = "Sleep Environment Lignoceric Acid"
    case sleepEnvironmentCeroticAcid = "Sleep Environment Cerotic Acid"
    case sleepEnvironmentMontanicAcid = "Sleep Environment Montanic Acid"
    case sleepEnvironmentMelissicAcid = "Sleep Environment Melissic Acid"
    case sleepEnvironmentOleicAcid = "Sleep Environment Oleic Acid"
    case sleepEnvironmentLinoleicAcid = "Sleep Environment Linoleic Acid"
    case sleepEnvironmentAlphaLinolenicAcid = "Sleep Environment Alpha Linolenic Acid"
    case sleepEnvironmentArachidonicAcid = "Sleep Environment Arachidonic Acid"
    case sleepEnvironmentEicosapentaenoicAcid = "Sleep Environment Eicosapentaenoic Acid"
    case sleepEnvironmentDocosahexaenoicAcid = "Sleep Environment Docosahexaenoic Acid"
    case sleepEnvironmentErucicAcid = "Sleep Environment Erucic Acid"
    case sleepEnvironmentNervonicAcid = "Sleep Environment Nervonic Acid"
    case sleepEnvironmentRicinoleicAcid = "Sleep Environment Ricinoleic Acid"
    case sleepEnvironmentConjugatedLinoleicAcid = "Sleep Environment Conjugated Linoleic Acid"
    case sleepEnvironmentTransFattyAcids = "Sleep Environment Trans Fatty Acids"
    case sleepEnvironmentSaturatedFattyAcids = "Sleep Environment Saturated Fatty Acids"
    case sleepEnvironmentMonounsaturatedFattyAcids = "Sleep Environment Monounsaturated Fatty Acids"
    case sleepEnvironmentPolyunsaturatedFattyAcids = "Sleep Environment Polyunsaturated Fatty Acids"
    case sleepEnvironmentOmega3FattyAcids = "Sleep Environment Omega 3 Fatty Acids"
    case sleepEnvironmentOmega6FattyAcids = "Sleep Environment Omega 6 Fatty Acids"
    case sleepEnvironmentOmega9FattyAcids = "Sleep Environment Omega 9 Fatty Acids"
    case sleepEnvironmentCholesterol = "Sleep Environment Cholesterol"
    case sleepEnvironmentSodium = "Sleep Environment Sodium"
    case sleepEnvironmentPotassium = "Sleep Environment Potassium"
    case sleepEnvironmentChloride = "Sleep Environment Chloride"
    case sleepEnvironmentCalcium = "Sleep Environment Calcium"
    case sleepEnvironmentMagnesium = "Sleep Environment Magnesium"
    case sleepEnvironmentPhosphorus = "Sleep Environment Phosphorus"
    case sleepEnvironmentSulfur = "Sleep Environment Sulfur"
    case sleepEnvironmentIron = "Sleep Environment Iron"
    case sleepEnvironmentZinc = "Sleep Environment Zinc"
    case sleepEnvironmentCopper = "Sleep Environment Copper"
    case sleepEnvironmentManganese = "Sleep Environment Manganese"
    case sleepEnvironmentIodine = "Sleep Environment Iodine"
    case sleepEnvironmentSelenium = "Sleep Environment Selenium"
    case sleepEnvironmentMolybdenum = "Sleep Environment Molybdenum"
    case sleepEnvironmentChromium = "Sleep Environment Chromium"
    case sleepEnvironmentFluoride = "Sleep Environment Fluoride"
    case sleepEnvironmentCobalt = "Sleep Environment Cobalt"
    case sleepEnvironmentNickel = "Sleep Environment Nickel"
    case sleepEnvironmentVanadium = "Sleep Environment Vanadium"
    case sleepEnvironmentSilicon = "Sleep Environment Silicon"
    case sleepEnvironmentBoron = "Sleep Environment Boron"
    case sleepEnvironmentArsenic = "Sleep Environment Arsenic"
    case sleepEnvironmentLead = "Sleep Environment Lead"
    case sleepEnvironmentMercury = "Sleep Environment Mercury"
    case sleepEnvironmentCadmium = "Sleep Environment Cadmium"
    case sleepEnvironmentAluminum = "Sleep Environment Aluminum"
    case sleepEnvironmentTin = "Sleep Environment Tin"
    case sleepEnvironmentLithium = "Sleep Environment Lithium"
    case sleepEnvironmentRubidium = "Sleep Environment Rubidium"
    case sleepEnvironmentCesium = "Sleep Environment Cesium"
    case sleepEnvironmentBarium = "Sleep Environment Barium"
    case sleepEnvironmentStrontium = "Sleep Environment Strontium"
    case sleepEnvironmentBromine = "Sleep Environment Bromine"
    case sleepEnvironmentChlorineGas = "Sleep Environment Chlorine Gas"
    case sleepEnvironmentFluorineGas = "Sleep Environment Fluorine Gas"
    case sleepEnvironmentIodineGas = "Sleep Environment Iodine Gas"
    case sleepEnvironmentOzoneGas = "Sleep Environment Ozone Gas"
    case sleepEnvironmentRadonGas = "Sleep Environment Radon Gas"
    case sleepEnvironmentCarbonMonoxideGas = "Sleep Environment Carbon Monoxide Gas"
    case sleepEnvironmentNitrogenDioxideGas = "Sleep Environment Nitrogen Dioxide Gas"
    case sleepEnvironmentSulfurDioxideGas = "Sleep Environment Sulfur Dioxide Gas"
    case sleepEnvironmentHydrogenSulfideGas = "Sleep Environment Hydrogen Sulfide Gas"
    case sleepEnvironmentAmmoniaGas = "Sleep Environment Ammonia Gas"
    case sleepEnvironmentMethaneGas = "Sleep Environment Methane Gas"
    case sleepEnvironmentFormaldehydeGas = "Sleep Environment Formaldehyde Gas"
    case sleepEnvironmentBenzene = "Sleep Environment Benzene"
    case sleepEnvironmentToluene = "Sleep Environment Toluene"
    case sleepEnvironmentXylene = "Sleep Environment Xylene"
    case sleepEnvironmentEthylbenzene = "Sleep Environment Ethylbenzene"
    case sleepEnvironmentStyrene = "Sleep Environment Styrene"
    case sleepEnvironmentNaphthalene = "Sleep Environment Naphthalene"
    case sleepEnvironmentPhenol = "Sleep Environment Phenol"
    case sleepEnvironmentCreosote = "Sleep Environment Creosote"
    case sleepEnvironmentPesticides = "Sleep Environment Pesticides"
    case sleepEnvironmentHerbicides = "Sleep Environment Herbicide"
    case sleepEnvironmentFungicides = "Sleep Environment Fungicides"
    case sleepEnvironmentInsecticides = "Sleep Environment Insecticides"
    case sleepEnvironmentRodenticides = "Sleep Environment Rodenticides"
    case sleepEnvironmentDisinfectants = "Sleep Environment Disinfectants"
    case sleepEnvironmentCleaningAgents = "Sleep Environment Cleaning Agents"
    case sleepEnvironmentPersonalCareProducts = "Sleep Environment Personal Care Products"
    case sleepEnvironmentBuildingMaterials = "Sleep Environment Building Materials"
    case sleepEnvironmentFurnishings = "Sleep Environment Furnishings"
    case sleepEnvironmentElectronics = "Sleep Environment Electronics"
    case sleepEnvironmentPlastics = "Sleep Environment Plastics"
    case sleepEnvironmentTextiles = "Sleep Environment Textiles"
    case sleepEnvironmentPaints = "Sleep Environment Paints"
    case sleepEnvironmentAdhesives = "Sleep Environment Adhesives"
    case sleepEnvironmentSolvents = "Sleep Environment Solvents"
    case sleepEnvironmentCombustionByproducts = "Sleep Environment Combustion Byproducts"
    case sleepEnvironmentAllergens = "Sleep Environment Allergens"
    case sleepEnvironmentMoldSpores = "Sleep Environment Mold Spores"
    case sleepEnvironmentDustMites = "Sleep Environment Dust Mites"
    case sleepEnvironmentPetDander = "Sleep Environment Pet Dander"
    case sleepEnvironmentPollen = "Sleep Environment Pollen"
    case sleepEnvironmentBacteria = "Sleep Environment Bacteria"
    case sleepEnvironmentViruses = "Sleep Environment Viruses"
    case sleepEnvironmentFungi = "Sleep Environment Fungi"
    case sleepEnvironmentProtozoa = "Sleep Environment Protozoa"
    case sleepEnvironmentParasites = "Sleep Environment Parasites"
    case sleepEnvironmentEndotoxins = "Sleep Environment Endotoxins"
    case sleepEnvironmentExotoxins = "Sleep Environment Exotoxins"
    case sleepEnvironmentMycotoxins = "Sleep Environment Mycotoxins"
    case sleepEnvironmentAflatoxins = "Sleep Environment Aflatoxins"
    case sleepEnvironmentOchratoxins = "Sleep Environment Ochratoxins"
    case sleepEnvironmentFumonisins = "Sleep Environment Fumonisins"
    case sleepEnvironmentZearalenone = "Sleep Environment Zearalenone"
    case sleepEnvironmentDeoxynivalenol = "Sleep Environment Deoxynivalenol"
    case sleepEnvironmentT2Toxin = "Sleep Environment T2 Toxin"
    case sleepEnvironmentHT2Toxin = "Sleep Environment HT2 Toxin"
    case sleepEnvironmentPatulin = "Sleep Environment Patulin"
    case sleepEnvironmentCitrinin = "Sleep Environment Citrinin"
    case sleepEnvironmentErgotAlkaloids = "Sleep Environment Ergot Alkaloids"
    case sleepEnvironmentCyanotoxins = "Sleep Environment Cyanotoxins"
    case sleepEnvironmentSaxitoxin = "Sleep Environment Saxitoxin"
    case sleepEnvironmentNodularin = "Sleep Environment Nodularin"
    case sleepEnvironmentMicrocystin = "Sleep Environment Microcystin"
    case sleepEnvironmentAnatoxinA = "Sleep Environment Anatoxin A"
    case sleepEnvironmentCylindrospermopsin = "Sleep Environment Cylindrospermopsin"
    case sleepEnvironmentBrevetoxin = "Sleep Environment Brevetoxin"
    case sleepEnvironmentDomoicAcid = "Sleep Environment Domoic Acid"
    case sleepEnvironmentOkadaicAcid = "Sleep Environment Okadaic Acid"
    case sleepEnvironmentPalytoxin = "Sleep Environment Palytoxin"
    case sleepEnvironmentCiguatoxin = "Sleep Environment Ciguatoxin"
    case sleepEnvironmentTetrodotoxin = "Sleep Environment Tetrodotoxin"
    case sleepEnvironmentBotulinumToxin = "Sleep Environment Botulinum Toxin"
    case sleepEnvironmentTetanusToxin = "Sleep Environment Tetanus Toxin"
    case sleepEnvironmentDiphtheriaToxin = "Sleep Environment Diphtheria Toxin"
    case sleepEnvironmentCholeraToxin = "Sleep Environment Cholera Toxin"
    case sleepEnvironmentShigaToxin = "Sleep Environment Shiga Toxin"
    case sleepEnvironmentPertussisToxin = "Sleep Environment Pertussis Toxin"
    case sleepEnvironmentAnthraxToxin = "Sleep Environment Anthrax Toxin"
    case sleepEnvironmentRicin = "Sleep Environment Ricin"
    case sleepEnvironmentAbrin = "Sleep Environment Abrin"
    case sleepEnvironmentConiine = "Sleep Environment Coniine"
    case sleepEnvironmentSolanine = "Sleep Environment Solanine"
    case sleepEnvironmentAconitine = "Sleep Environment Aconitine"
    case sleepEnvironmentStrychnine = "Sleep Environment Strychnine"
    case sleepEnvironmentAtropine = "Sleep Environment Atropine"
    case sleepEnvironmentScopolamine = "Sleep Environment Scopolamine"
    case sleepEnvironmentHyoscyamine = "Sleep Environment Hyoscyamine"
    case sleepEnvironmentCocaine = "Sleep Environment Cocaine"
    case sleepEnvironmentMorphine = "Sleep Environment Morphine"
    case sleepEnvironmentCodeine = "Sleep Environment Codeine"
    case sleepEnvironmentHeroin = "Sleep Environment Heroin"
    case sleepEnvironmentNicotine = "Sleep Environment Nicotine"
    case sleepEnvironmentCaffeine = "Sleep Environment Caffeine"
    case sleepEnvironmentEthanol = "Sleep Environment Ethanol"
    case sleepEnvironmentMethanol = "Sleep Environment Methanol"
    case sleepEnvironmentEthyleneGlycol = "Sleep Environment Ethylene Glycol"
    case sleepEnvironmentPropyleneGlycol = "Sleep Environment Propylene Glycol"
    case sleepEnvironmentAcetone = "Sleep Environment Acetone"
    case sleepEnvironmentBenzeneVapor = "Sleep Environment Benzene Vapor"
    case sleepEnvironmentTolueneVapor = "Sleep Environment Toluene Vapor"
    case sleepEnvironmentXyleneVapor = "Sleep Environment Xylene Vapor"
    case sleepEnvironmentEthylbenzeneVapor = "Sleep Environment Ethylbenzene Vapor"
    case sleepEnvironmentStyreneVapor = "Sleep Environment Styrene Vapor"
    case sleepEnvironmentNaphthaleneVapor = "Sleep Environment Naphthalene Vapor"
    case sleepEnvironmentPhenolVapor = "Sleep Environment Phenol Vapor"
    case sleepEnvironmentCreosoteVapor = "Sleep Environment Creosote Vapor"
    case sleepEnvironmentPesticideVapor = "Sleep Environment Pesticide Vapor"
    case sleepEnvironmentHerbicideVapor = "Sleep Environment Herbicide Vapor"
    case sleepEnvironmentFungicideVapor = "Sleep Environment Fungicide Vapor"
    case sleepEnvironmentInsecticideVapor = "Sleep Environment Insecticide Vapor"
    case sleepEnvironmentRodenticideVapor = "Sleep Environment Rodenticide Vapor"
    case sleepEnvironmentDisinfectantVapor = "Sleep Environment Disinfectant Vapor"
    case sleepEnvironmentCleaningAgentVapor = "Sleep Environment Cleaning Agent Vapor"
    case sleepEnvironmentPersonalCareProductVapor = "Sleep Environment Personal Care Product Vapor"
    case sleepEnvironmentBuildingMaterialVapor = "Sleep Environment Building Material Vapor"
    case sleepEnvironmentFurnishingVapor = "Sleep Environment Furnishing Vapor"
    case sleepEnvironmentElectronicsVapor = "Sleep Environment Electronics Vapor"
    case sleepEnvironmentPlasticsVapor = "Sleep Environment Plastics Vapor"
    case sleepEnvironmentTextilesVapor = "Sleep Environment Textiles Vapor"
    case sleepEnvironmentPaintsVapor = "Sleep Environment Paints Vapor"
    case sleepEnvironmentAdhesivesVapor = "Sleep Environment Adhesives Vapor"
    case sleepEnvironmentSolventsVapor = "Sleep Environment Solvents Vapor"
    case sleepEnvironmentCombustionByproductVapor = "Sleep Environment Combustion Byproduct Vapor"
    case sleepEnvironmentAllergenConcentration = "Sleep Environment Allergen Concentration"
    case sleepEnvironmentMoldSporeConcentration = "Sleep Environment Mold Spore Concentration"
    case sleepEnvironmentDustMiteConcentration = "Sleep Environment Dust Mite Concentration"
    case sleepEnvironmentPetDanderConcentration = "Sleep Environment Pet Dander Concentration"
    case sleepEnvironmentPollenConcentration = "Sleep Environment Pollen Concentration"
    case sleepEnvironmentBacteriaConcentration = "Sleep Environment Bacteria Concentration"
    case sleepEnvironmentVirusConcentration = "Sleep Environment Virus Concentration"
    case sleepEnvironmentFungiConcentration = "Sleep Environment Fungi Concentration"
    case sleepEnvironmentProtozoaConcentration = "Sleep Environment Protozoa Concentration"
    case sleepEnvironmentParasiteConcentration = "Sleep Environment Parasite Concentration"
    case sleepEnvironmentEndotoxinConcentration = "Sleep Environment Endotoxin Concentration"
    case sleepEnvironmentExotoxinConcentration = "Sleep Environment Exotoxin Concentration"
    case sleepEnvironmentMycotoxinConcentration = "Sleep Environment Mycotoxin Concentration"
    case sleepEnvironmentAflatoxinConcentration = "Sleep Environment Aflatoxin Concentration"
    case sleepEnvironmentOchratoxinConcentration = "Sleep Environment Ochratoxin Concentration"
    case sleepEnvironmentFumonisinConcentration = "Sleep Environment Fumonisin Concentration"
    case sleepEnvironmentZearalenoneConcentration = "Sleep Environment Zearalenone Concentration"
    case sleepEnvironmentDeoxynivalenolConcentration = "Sleep Environment Deoxynivalenol Concentration"
    case sleepEnvironmentT2ToxinConcentration = "Sleep Environment T2 Toxin Concentration"
    case sleepEnvironmentHT2ToxinConcentration = "Sleep Environment HT2 Toxin Concentration"
    case sleepEnvironmentPatulinConcentration = "Sleep Environment Patulin Concentration"
    case sleepEnvironmentCitrininConcentration = "Sleep Environment Citrinin Concentration"
    case sleepEnvironmentErgotAlkaloidConcentration = "Sleep Environment Ergot Alkaloid Concentration"
    case sleepEnvironmentCyanotoxinConcentration = "Sleep Environment Cyanotoxin Concentration"
    case sleepEnvironmentSaxitoxinConcentration = "Sleep Environment Saxitoxin Concentration"
    case sleepEnvironmentNodularinConcentration = "Sleep Environment Nodularin Concentration"
    case sleepEnvironmentMicrocystinConcentration = "Sleep Environment Microcystin Concentration"
    case sleepEnvironmentAnatoxinAConcentration = "Sleep Environment Anatoxin A Concentration"
    case sleepEnvironmentCylindrospermopsinConcentration = "Sleep Environment Cylindrospermopsin Concentration"
    case sleepEnvironmentBrevetoxinConcentration = "Sleep Environment Brevetoxin Concentration"
    case sleepEnvironmentDomoicAcidConcentration = "Sleep Environment Domoic Acid Concentration"
    case sleepEnvironmentOkadaicAcidConcentration = "Sleep Environment Okadaic Acid Concentration"
    case sleepEnvironmentPalytoxinConcentration = "Sleep Environment Palytoxin Concentration"
    case sleepEnvironmentCiguatoxinConcentration = "Sleep Environment Ciguatoxin Concentration"
    case sleepEnvironmentTetrodotoxinConcentration = "Sleep Environment Tetrodotoxin Concentration"
    case sleepEnvironmentBotulinumToxinConcentration = "Sleep Environment Botulinum Toxin Concentration"
    case sleepEnvironmentTetanusToxinConcentration = "Sleep Environment Tetanus Toxin Concentration"
    case sleepEnvironmentDiphtheriaToxinConcentration = "Sleep Environment Diphtheria Toxin Concentration"
    case sleepEnvironmentCholeraToxinConcentration = "Sleep Environment Cholera Toxin Concentration"
    case sleepEnvironmentShigaToxinConcentration = "Sleep Environment Shiga Toxin Concentration"
    case sleepEnvironmentPertussisToxinConcentration = "Sleep Environment Pertussis Toxin Concentration"
    case sleepEnvironmentAnthraxToxinConcentration = "Sleep Environment Anthrax Toxin Concentration"
    case sleepEnvironmentRicinConcentration = "Sleep Environment Ricin Concentration"
    case sleepEnvironmentAbrinConcentration = "Sleep Environment Abrin Concentration"
    case sleepEnvironmentConiineConcentration = "Sleep Environment Coniine Concentration"
    case sleepEnvironmentSolanineConcentration = "Sleep Environment Solanine Concentration"
    case sleepEnvironmentAconitineConcentration = "Sleep Environment Aconitine Concentration"
    case sleepEnvironmentStrychnineConcentration = "Sleep Environment Strychnine Concentration"
    case sleepEnvironmentAtropineConcentration = "Sleep Environment Atropine Concentration"
    case sleepEnvironmentScopolamineConcentration = "Sleep Environment Scopolamine Concentration"
    case sleepEnvironmentHyoscyamineConcentration = "Sleep Environment Hyoscyamine Concentration"
    case sleepEnvironmentCocaineConcentration = "Sleep Environment Cocaine Concentration"
    case sleepEnvironmentMorphineConcentration = "Sleep Environment Morphine Concentration"
    case sleepEnvironmentCodeineConcentration = "Sleep Environment Codeine Concentration"
    case sleepEnvironmentHeroinConcentration = "Sleep Environment Heroin Concentration"
    case sleepEnvironmentNicotineConcentration = "Sleep Environment Nicotine Concentration"
    case sleepEnvironmentCaffeineConcentration = "Sleep Environment Caffeine Concentration"
    case sleepEnvironmentEthanolConcentration = "Sleep Environment Ethanol Concentration"
    case sleepEnvironmentMethanolConcentration = "Sleep Environment Methanol Concentration"
    case sleepEnvironmentEthyleneGlycolConcentration = "Sleep Environment Ethylene Glycol Concentration"
    case sleepEnvironmentPropyleneGlycolConcentration = "Sleep Environment Propylene Glycol Concentration"
    case sleepEnvironmentAcetoneConcentration = "Sleep Environment Acetone Concentration"
    case sleepEnvironmentBenzeneVaporConcentration = "Sleep Environment Benzene Vapor Concentration"
    case sleepEnvironmentTolueneVaporConcentration = "Sleep Environment Toluene Vapor Concentration"
    case sleepEnvironmentXyleneVaporConcentration = "Sleep Environment Xylene Vapor Concentration"
    case sleepEnvironmentEthylbenzeneVaporConcentration = "Sleep Environment Ethylbenzene Vapor Concentration"
    case sleepEnvironmentStyreneVaporConcentration = "Sleep Environment Styrene Vapor Concentration"
    case sleepEnvironmentNaphthaleneVaporConcentration = "Sleep Environment Naphthalene Vapor Concentration"
    case sleepEnvironmentPhenolVaporConcentration = "Sleep Environment Phenol Vapor Concentration"
    case sleepEnvironmentCreosoteVaporConcentration = "Sleep Environment Creosote Vapor Concentration"
    case sleepEnvironmentPesticideVaporConcentration = "Sleep Environment Pesticide Vapor Concentration"
    case sleepEnvironmentHerbicideVaporConcentration = "Sleep Environment Herbicide Vapor Concentration"
    case sleepEnvironmentFungicideVaporConcentration = "Sleep Environment Fungicide Vapor Concentration"
    case sleepEnvironmentInsecticideVaporConcentration = "Sleep Environment Insecticide Vapor Concentration"
    case sleepEnvironmentRodenticideVaporConcentration = "Sleep Environment Rodenticide Vapor Concentration"
    case sleepEnvironmentDisinfectantVaporConcentration = "Sleep Environment Disinfectant Vapor Concentration"
    case sleepEnvironmentCleaningAgentVaporConcentration = "Sleep Environment Cleaning Agent Vapor Concentration"
    case sleepEnvironmentPersonalCareProductVaporConcentration = "Sleep Environment Personal Care Product Vapor Concentration"
    case sleepEnvironmentBuildingMaterialVaporConcentration = "Sleep Environment Building Material Vapor Concentration"
    case sleepEnvironmentFurnishingVaporConcentration = "Sleep Environment Furnishing Vapor Concentration"
    case sleepEnvironmentElectronicsVaporConcentration = "Sleep Environment Electronics Vapor Concentration"
    case sleepEnvironmentPlasticsVaporConcentration = "Sleep Environment Plastics Vapor Concentration"
    case sleepEnvironmentTextilesVaporConcentration = "Sleep Environment Textiles Vapor Concentration"
    case sleepEnvironmentPaintsVaporConcentration = "Sleep Environment Paints Vapor Concentration"
    case sleepEnvironmentAdhesivesVaporConcentration = "Sleep Environment Adhesives Vapor Concentration"
    case sleepEnvironmentSolventsVaporConcentration = "Sleep Environment Solvents Vapor Concentration"
    case sleepEnvironmentCombustionByproductVaporConcentration = "Sleep Environment Combustion Byproduct Vapor Concentration"
}

/// Represents a user's health data entry for analytics and the Digital Health Twin.
///
/// - Stores both numerical and string-based health data, with optional metadata.
@Model
public class HealthDataEntry: Identifiable {
    @Attribute(.unique) var id: UUID
    var timestamp: Date
    var dataType: HealthDataType
    var value: Double // Generic value for numerical data
    var stringValue: String? // For non-numerical data like genomic or clinical records
    var unit: String? // e.g., "hours", "steps", "bpm", "mg/dL"
    var source: String? // e.g., "HealthKit", "Manual Input", "23andMe"
    var deviceSource: String? // e.g., "iPhone", "Apple Watch", "Smart Ring"
    var provenance: String? // e.g., "HealthKit API", "User Input", "Third-Party Integration"
    var metadata: Data? // For storing additional structured metadata (e.g., JSON)
    var isValidated: Bool // Indicates if data has passed validation checks
    var validationErrors: [String]? // Stores any validation errors
    @Relationship(deleteRule: .cascade) var relatedMetrics: [RelatedMetric]?

    public init(id: UUID = UUID(), timestamp: Date, dataType: HealthDataType, value: Double, stringValue: String? = nil, unit: String? = nil, source: String? = nil, deviceSource: String? = nil, provenance: String? = nil, metadata: Data? = nil, isValidated: Bool = true, validationErrors: [String]? = nil) {
        self.id = id
        self.timestamp = timestamp
        self.dataType = dataType
        self.value = value
        self.stringValue = stringValue
        self.unit = unit
        self.source = source
        self.deviceSource = deviceSource
        self.provenance = provenance
        self.metadata = metadata
        self.isValidated = isValidated
        self.validationErrors = validationErrors
    }

    // Computed properties for formatted display and analytics.
    public var formattedValue: String {
        if let stringValue = stringValue, !stringValue.isEmpty {
            return stringValue
        }
        return String(format: "%.2f %@", value, unit ?? "")
    }

    public var isNumerical: Bool {
        return stringValue == nil
    }

    // Basic validation example
    public func validate() {
        var errors: [String] = []
        if value < 0 {
            errors.append("Value cannot be negative.")
        }
        // Add more specific validation rules based on dataType
        isValidated = errors.isEmpty
        validationErrors = errors.isEmpty ? nil : errors
    }
}

@Model
class RelatedMetric {
    @Attribute(.unique) var id: UUID
    var metricName: String
    var metricValue: Double

    init(id: UUID = UUID(), metricName: String, metricValue: Double) {
        self.id = id
        self.metricName = metricName
        self.metricValue = metricValue
    }
}

// Example query usage with SwiftData
func fetchHealthDataEntries(forType type: String, in context: ModelContext) -> [HealthDataEntry] {
    @Query(filter: #Predicate<HealthDataEntry> { entry in
        entry.dataType.rawValue == type
    }) var entries: [HealthDataEntry]
    return entries
}
