name: Continuous Integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer

jobs:
  # Swift Package Manager validation
  spm-validation:
    name: Swift Package Manager Validation
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
    
    - name: Swift version
      run: swift --version
    
    - name: Validate Package.swift
      run: swift package dump-package > /dev/null
    
    - name: Build Package
      run: swift build
    
    - name: Run Package Tests
      run: swift test --parallel

  # Code Quality Checks
  code-quality:
    name: Code Quality Analysis
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Check for TODO/FIXME
      run: |
        TODO_COUNT=$(grep -r "TODO\|FIXME" --include="*.swift" . | wc -l)
        echo "Found $TODO_COUNT TODO/FIXME items"
        if [ $TODO_COUNT -gt 125 ]; then
          echo "❌ Too many TODO/FIXME items ($TODO_COUNT). Maximum allowed: 125"
          exit 1
        else
          echo "✅ TODO/FIXME count is acceptable ($TODO_COUNT/125)"
        fi
    
    - name: Check file sizes
      run: |
        LARGE_FILES=$(find . -name "*.swift" -size +50k | wc -l)
        echo "Found $LARGE_FILES files larger than 50KB"
        if [ $LARGE_FILES -gt 8 ]; then
          echo "❌ Too many large files ($LARGE_FILES). Consider refactoring."
          find . -name "*.swift" -size +50k -exec wc -l {} + | sort -nr | head -10
          exit 1
        else
          echo "✅ File sizes are reasonable ($LARGE_FILES large files)"
        fi

  # Accessibility Testing
  accessibility-tests:
    name: Accessibility Validation
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Validate Accessibility Implementation
      run: |
        echo "♿ Validating accessibility implementation..."
        
        # Check accessibility helper usage
        ACCESSIBILITY_USAGE=$(grep -r "AccessibilityHelper\|accessibilityLabel\|accessibilityHint" --include="*.swift" . | wc -l)
        echo "Found $ACCESSIBILITY_USAGE accessibility implementations"
        
        if [ $ACCESSIBILITY_USAGE -lt 50 ]; then
          echo "❌ Insufficient accessibility implementation ($ACCESSIBILITY_USAGE). Need at least 50."
          exit 1
        else
          echo "✅ Accessibility implementation looks comprehensive ($ACCESSIBILITY_USAGE implementations)"
        fi

  # Integration Status
  ci-status:
    name: CI Status
    runs-on: ubuntu-latest
    needs: [spm-validation, code-quality, accessibility-tests]
    if: always()
    steps:
    - name: Check CI Results
      run: |
        if [[ "${{ needs.smp-validation.result }}" == "success" && \
              "${{ needs.code-quality.result }}" == "success" && \
              "${{ needs.accessibility-tests.result }}" == "success" ]]; then
          echo "✅ All CI checks passed successfully\!"
        else
          echo "❌ Some CI checks failed"
          exit 1
        fi
EOF < /dev/null