# Example Trivy scan step for CI
# Already included in ci.yml, but here is a standalone example

name: Trivy Scan

on:
  workflow_dispatch:

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t healthai2030:ci .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'healthai2030:ci'
